interface agency {
  id: number;
  url: string;
  name: string;
  type: string;
}
interface ProgramType {
  id: number | null;
  url: string | null;
  name: string | null;
  description: string | null;
  agencies: agency[];
  image_url: string | null;
  start_date: string | null;
  end_date: string | null;
  info_url: string | null;
  wiki_url: string | null;
  mission_patches: Array<any>;
}

export interface NextType {
  id: string;
  url: string;
  slug: string;
  flightclub_url: string | null;
  r_spacex_api_id: string | null;
  name: string;
  status?: {
    id: number;
    name: string;
    abbrev: string;
    description: string;
  };
  last_updated: string;
  updates: {
    id: number;
    profile_image: string;
    comment: string;
    info_url: string;
    created_by: string;
    created_on: string;
  }[];
  net: string;
  window_end: string;
  window_start: string;
  probability: number | null;
  holdreason: string | null;
  failreason: string | null;
  hashtag: string | null;
  launch_service_provider?: {
    id: number;
    url: string;
    name?: string;
    type: string;
    country_code: string;
    abbrev: string;
    description: string;
    administrator: string;
    founding_year: string;
    launchers: string;
    spacecraft: string;
    launch_library_url: string;
    total_launch_count: number;
    consecutive_successful_launches: number;
    successful_launches: number;
    failed_launches: number;
    pending_launches: number;
    consecutive_successful_landings: number;
    successful_landings: number;
    failed_landings: number;
    attempted_landings: number;
    info_url: string;
    wiki_url: string;
    logo_url: string;
    image_url: string;
    nation_url: string;
  };
  rocket?: {
    id: number;
    configuration: {
      id: number;
      url: string;
      name: string;
      description: string;
      family: string;
      full_name: string;
      manufacturer: {
        id: number;
        url: string;
        name: string;
        featured: boolean;
        type: string;
        country_code: string;
        abbrev: string;
        description: string;
        administrator: string;
        founding_year: string;
        launchers: string;
        spacecraft: string;
        launch_library_url: string;
        total_launch_count: number;
        consecutive_successful_launches: number;
        successful_launches: number;
        failed_launches: number;
        pending_launches: number;
        consecutive_successful_landings: number;
        successful_landings: number;
        failed_landings: number;
        attempted_landings: number;
        info_url: string;
        wiki_url: string;
        logo_url: string;
        image_url: string | null;
        nation_url: string | null;
      };
      program: [];
      variant: string;
      alias: string;
      min_stage: number;
      max_stage: number;
      length: number;
      diameter: number;
      maiden_flight: string;
      launch_cost: string;
      launch_mass: number;
      leo_capacity: number;
      gto_capacity: number | null;
      to_thrust: number;
      apogee: number | null;
      vehicle_range: number | null;
      image_url: string | null;
      info_url: string | null;
      wiki_url: string | null;
      total_launch_count: number;
      consecutive_successful_launches: number;
      successful_launches: number;
      failed_launches: number;
      pending_launches: number;
    };
    launcher_stage: [];
    spacecraft_stage: string | null;
  };
  mission: {
    id: number;
    name: string;
    description: string;
    launch_designator: string | null;
    type: string;
    orbit: {
      id: number;
      name: string;
      abbrev: string;
    };
  } | null;
  pad: {
    id: number;
    url: string;
    agency_id: number | null;
    name: string;
    info_url: string | null;
    wiki_url: string;
    map_url: string;
    latitude: string;
    longitude: string;
    location: {
      id: number;
      url: string;
      name: string;
      country_code: string;
      map_image: string;
      total_launch_count: number;
      total_landing_count: number;
    };
    map_image: string;
    total_launch_count: number;
  };
  infoURLs: [];
  vidURLs: {
    priority: number | null;
    title: string;
    description: string;
    feature_image: string;
    url: string;
  }[];
  webcast_live: boolean | string;
  image: string;
  infographic: string | null;
  program: Array<ProgramType> | [];
  orbital_launch_attempt_count: number | null;
  location_launch_attempt_count: number | null;
  pad_launch_attempt_count: number | null;
  agency_launch_attempt_count: number | null;
  orbital_launch_attempt_count_year: number | null;
  location_launch_attempt_count_year: number | null;
  pad_launch_attempt_count_year: number | null;
  agency_launch_attempt_count_year: number | null;
  mission_patches: [];
}
