import { Settings } from "./interfaces/settings";

const settings: Settings = {
  GUILD_ID: "YOUR GUILD ID",
  CLIENT_ID: "YOUR CLIENT ID",
  CLIENT_TOKEN: "YOUR CLIENT TOKEN",
  LAUNCH_API_TOKEN: "EXTERNAL API TOKEN",
  NASA_API_TOKEN: "YOUR NASA API TOKEN",
  DATABASE: {
    DATABASE_URL: "DATABASE URL",
    DATABASE_NAME: "DATABASE NAME",
    DATABASE_PASSWORD: "DATABASE PASSWORD",
    LAUNCHES_COLLECTION_NAME: "LAUNCH COLLECTION NAME",
    GUILDS_COLLECTION_NAME: "GUILDS COLLECTION NAME",
  },
};

export default settings;
